export { default as ContactSection } from "~/components/svelte/contact-section.svelte";
export { default as Footer } from "~/components/svelte/footer.svelte";
export { default as HeroSection } from "~/components/svelte/hero-section.svelte";
export { default as Logo } from "~/components/svelte/logo.svelte";
export { default as Menu } from "~/components/svelte/menu.svelte";
export { default as Project } from "~/components/svelte/project.svelte";
export { default as ProjectsSection } from "~/components/svelte/projects-section.svelte";
export { default as Service } from "~/components/svelte/service.svelte";
export { default as ServicesSection } from "~/components/svelte/services-section.svelte";
